@startuml ユースケース図
actor 利用者
    rectangle キャンペーン中のホテル宿泊予約{
        usecase ログインする
        usecase (<u>予約する</u>\n拡張点\nキャンペーン期間中) as input
        usecase キャンペーン価格にする
    }
    (キャンペーン価格にする) .>input : <<extend>>
    input .> ログインする : << include >>
    利用者  -> input
    @enduml