@startuml 演習4-5
skinparam style strictuml

actor ":会員" as user
participant ":商品検索画面" as screen
participant ":商品コントローラ" as control
participant ":商品" as entity

activate user
user -> screen : 商品検索(商品番号)
activate screen
screen -> control : 商品検索(商品番号)
activate control
create entity
control -->> entity :<<entity>>生成()

loop 商品のカテゴリ数
create ":商品カテゴリ" as category
control -->> category : <<entity>>生成()
control -> entity : 商品カテゴリ設定()
activate entity
deactivate entity

end loop

screen <<-- control : 商品情報
screen  -> screen : 商品情報表示(商品情報)
activate screen

deactivate 
@enduml
